default_roles:
  - zsh
  - btop
  - git
  - terraform
  - pyenv
  - system
  - k8s
  - k9s
  - fonts
  - alacritty
  - desktop-apps
  - i3

git_user_name: "ramonvermeulen"
git_user_email: "ramonvermeulen98@gmail.com"
