---
- name: "nvm | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
  register: nvm_latest_version_json
  changed_when: false

- name: "nvm | Registering nvm Latest Release"
  ansible.builtin.set_fact:
    nvm_latest_release: "{{ nvm_latest_version_json.json.tag_name }}"

- name: "nvm | Registering nvm Latest Version"
  ansible.builtin.set_fact:
    nvm_latest_version: "{{ nvm_latest_release.stdout|default('') }}"

- name: "nvm | Getting version information"
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/nvm version -s | grep -o 'v[0-9]*\.[0-9]*\.[0-9]*'
  register: current_nvm_version
  changed_when: false
  failed_when: false

- name: "nvm | Show current_nvm_version debug"
  ansible.builtin.debug:
    var: current_nvm_version.stdout

- name: "nvm | Show nvm_latest_release debug"
  ansible.builtin.debug:
    var: nvm_latest_release

- name: "nvm | Install"
  block:
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_latest_release }}/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: nvm_latest_release not in current_nvm_version.stdout|default('')
  become: true

