# Ensure that Ansible gathers facts about installed packages
- name: "Desktop Apps | Gather installed package facts"
  ansible.builtin.package_facts:

# Check and install Google Chrome
- name: "Desktop Apps | install Chrome if not installed"
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true
  when: "'google-chrome-stable' not in ansible_facts.packages"

# Check and install Slack
- name: "Desktop Apps | install Slack if not installed"
  apt:
    deb: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.39.95/slack-desktop-4.39.95-amd64.deb
  become: true
  when: "'slack-desktop' not in ansible_facts.packages"

# Add GPG key for Spotify
- name: "Desktop Apps | add gpg key for spotify"
  ansible.builtin.apt_key:
    url: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
    state: present
    keyring: "/etc/apt/trusted.gpg.d/spotify.gpg"
  become: true

# Add Spotify APT repository
- name: "Desktop Apps | Add Spotify APT repository"
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/spotify.list"
    line: "deb http://repository.spotify.com stable non-free"
    create: yes
    mode: '0644'
  become: true

# Install Spotify
- name: "Desktop Apps | install Spotify"
  ansible.builtin.apt:
    name:
      - spotify-client
    state: present
    update_cache: true
  become: true

# Install IntelliJ Idea using snap
- name: "Desktop Apps | install IntelliJ Idea"
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
  become: true
