---
- name: "System | {{ ansible_distribution }} | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name:
      - jq
      # \/ required by pyenv for building python versions \/
      - aria2
      - build-essential
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - tk-dev
      - xz-utils
      - zlib1g-dev
      # general software
      - default-jre
      - vim 
      - gnome-tweaks # remap esc/caps
      # for WSL instances this is hany
      - ubuntu-desktop-minimal
      # some dependencies for the i3 setup
      - brightnessctl
      - blueman
      # GUI for xrandr e.g. handy when on multiple monitors
      - arandr
      - xclip
      - ripgrep
    state: present
  become: true
