---
- name: Zsh | Ensure zsh is installed
  apt:
    name: "zsh"
    state: present
    update-cache: yes
  become: true

- name: Zsh | Change default shell to zsh if not already set
  user:
    name: "{{ host_user }}"
    shell: /bin/zsh
