---
- name: Zsh | Ensure zsh is installed
  apt:
    name: "zsh"
    state: present
    update-cache: yes
  become: true

- name: Get current default shell of the user
  command: getent passwd "{{ host_user }}"
  register: user_info
  changed_when: false

- name: Zsh | Extract current shell
  set_fact:
    current_shell: "{{ user_info.stdout.split(':')[-1] | trim }}"

- name: Zsh | Change default shell to zsh if not already set
  user:
    name: "{{ host_user }}"
    shell: /bin/zsh
  when: current_shell != '/bin/zsh'
