---
- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "I3 | Copy over i3 config"
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: "0755"

- name: "I3 | Copy over .xinitrc"
  ansible.builtin.copy:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    mode: "0755"

- name: "I3 | Copy over .Xresources (frac scaling)"
  ansible.builtin.copy:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    mode: "0755"

- name: "I3 | Copy over change wallpaper script"
  ansible.builtin.copy:
    src: "replace_wallpaper.sh"
    dest: "{{ ansible_user_dir }}/replace_wallpaper.sh"
    mode: "0755"
