---
- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "I3 | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3"
    state: "directory"
    mode: "0755"
  become: true

- name: "I3 | Copy over i3 layout configs"
  synchronize:
    src: "layouts"
    dest: "{{ ansible_user_dir }}/.config/i3"
    recursive: true
    delete: false
  become: true

- name: "I3 | Copy over i3 config" 
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: "0755"
  become: true

- name: "I3 | Copy over i3 gaps config"
  ansible.builtin.copy:
    src: "i3-gaps-config"
    dest: "{{ ansible_user_dir }}/.config/i3/i3-gaps-config"
    mode: "0755"
  become: true

- name: "I3 | Copy over i3 startup config"
  ansible.builtin.copy:
    src: "startup-config"
    dest: "{{ ansible_user_dir }}/.config/i3/startup-config"
    mode: "0755"
  become: true


- name: "I3 | Copy over .xinitrc"
  ansible.builtin.copy:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    mode: "0755"
  become: true

- name: "I3 | Copy over .Xresources (frac scaling)"
  ansible.builtin.copy:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    mode: "0755"
  become: true

- name: "I3 | Copy over change wallpaper script"
  ansible.builtin.copy:
    src: "replace_wallpaper.sh"
    dest: "{{ ansible_user_dir }}/replace_wallpaper.sh"
    mode: "0755"
  become: true

- name: "I3 | Ensure picom directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/picom"
    state: "directory"
    mode: "0755"
  become: true

- name: "I3 | Copy over picom conf"
  ansible.builtin.copy:
    src: "picom.conf"
    dest: "{{ ansible_user_dir }}/.config/picom/picom.conf"
    mode: "0755"
  become: true


