---
- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "I3 | Copy over i3 config"
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: "0755"

- name: "I3 | Copy over polybar config"
  ansible.builtin.copy:
    src: "config.ini"
    dest: "{{ ansible_user_dir }}/.config/polybar/config.ini"
    mode: "0755"

- name: "I3 | Copy over polybar launch.sh"
  ansible.builtin.copy:
    src: "launch.sh"
    dest: "{{ ansible_user_dir }}/.config/polybar/launch.sh"
    mode: "0755"

- name: "I3 | Copy over .xinitrc"
  ansible.builtin.copy:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    mode: "0755"

- name: "I3 | Copy over .Xresources (frac scaling)"
  ansible.builtin.copy:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    mode: "0755"


