---
# the 'stat' blocks are added so config only gets created once
# because these are files you might want to change slightly per system
# if you need the new upstream verison simply delete the file and Ansible
# will recreate it for you
- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "I3 | Ensure config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3"
    state: "directory"
    mode: "0755"
  become: true

- name: "I3 | Check if config file exists"
  stat:
    path: "{{ ansible_user_dir }}/.config/i3/config"
  register: config_file_check

- name: "I3 | Copy over i3 config" 
  copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: "0755"
  become: true
  when: not config_file_check.stat.exists

- name: "I3 | Copy over i3 gaps config"
  ansible.builtin.copy:
    src: "i3-gaps-config"
    dest: "{{ ansible_user_dir }}/.config/i3/i3-gaps-config"
    mode: "0755"
  become: true

- name: "I3 | Check if startup-config file exists"
  stat:
    path: "{{ ansible_user_dir }}/.config/i3/startup-config"
  register: startup_file_check

- name: "I3 | Copy over i3 startup config"
  copy:
    src: "startup-config"
    dest: "{{ ansible_user_dir }}/.config/i3/startup-config"
    mode: "0755"
  when: not startup_file_check.stat.exists
  become: true

- name: "I3 | Copy over change wallpaper script"
  ansible.builtin.copy:
    src: "replace_wallpaper.sh"
    dest: "{{ ansible_user_dir }}/replace_wallpaper.sh"
    mode: "0755"
  become: true

- name: "I3 | Ensure picom directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/picom"
    state: "directory"
    mode: "0755"
  become: true

- name: "I3 | Copy over picom conf"
  ansible.builtin.copy:
    src: "picom.conf"
    dest: "{{ ansible_user_dir }}/.config/picom/picom.conf"
    mode: "0755"
  become: true

- name: "I3 | Copy over .xinitrc"
  ansible.builtin.copy:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    mode: "0755"
  become: true

- name: "I3 | Check if ~/.Xresources file exists"
  stat:
    path: "{{ ansible_user_dir }}/.Xresources"
  register: resources_file_check

- name: "I3 | Copy over .Xresources (frac scaling)"
  copy:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    mode: "0755"
  when: not resources_file_check.stat.exists
  become: true
