---
- name: "i3 | Install"
  ansible.builtin.apt:
    name: i3 
    state: present
  become: true

- name: "i3 | Install feh (wallpaper dependency)"
  ansible.builtin.apt:
    name: feh
    state: present
  become: true

- name: "i3 | Install picom (compositor)"
  ansible.builtin.apt:
    name: picom
    state: present
  become: true

- name: "i3 | Install bumblebee-status (top bar)"
  ansible.builtin.git:
    repo: "https://github.com/tobi-wan-kenobi/bumblebee-status"
    dest: "{{ ansible_user_dir }}/.config/bumblebee-status"
    version: "main"
    update: yes
  become: true

