---
- name: "Wezterm | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Wezterm | ensure config dir exists in .config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir}}/.config/wezterm"
    state: "directory"
    mode: "0755"

- name: "Wezterm | copy over wezterm.lua (config file)"
  ansible.builtin.copy:
    src: "wezterm.lua"
    dest: "{{ ansible_user_dir }}/.config/wezterm/wezterm.lua"
    mode: "0755"
