- name: "Wezterm | add gpg key"
  ansible.builtin.apt_key:
    url: "https://apt.fury.io/wez/gpg.key"
    state: present
    keyring: "/usr/share/keyrings/wezterm-fury.gpg"
  become: true

- name: "Wezterm | Add APT repository"
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
    filename: 'wezterm'
    state: present
  become: true

- name: "Wezterm | install"
  ansible.builtin.apt:
    name:
      - wezterm-nightly # as of now only (stable) one supported for ubuntu 24_04
    state: present
    update_cache: true
  become: true
