---
- name: "Pyenv | Install"
  block:
    - name: "Pyenv | Download pyenv install script"
      ansible.builtin.get_url:
        url: https://pyenv.run
        dest: /{{ ansible_user_dir }}/pyenv.install.sh
        force: true
        mode: "0755"
      notify:
        "Pyenv | Cleanup pyenv install script"

    - name: "Pyenv | Run the install script"
      ansible.builtin.script:
        cmd: /{{ ansible_user_dir }}/pyenv.install.sh
