---
- name: Remove oh-my-zsh Install Script
  ansible.builtin.file:
    path: /tmp/oh-my-zsh.install.sh
    state: absent

- name: Zsh | Cleanup oh-my-zsh install script
  ansible.builtin.file:
    path: /{{ ansible_user_dir }}/oh-my-zsh.install.sh
    state: absent
