---
- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Neovim | Ensure Neovim config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
    mode: 0755

- name: "Neovim | Copy config directory"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/"
    src: "nvim/"
    mode: 0644
